### ISSUE TITLE
autoSave does not work :-(

### ISSUE THREAD

**Issue by thetutlage** [oskosk/express-socket.io-session#11]
Here is an example which shows `autoSave` is not working

```javascript
'use strict'

var COOKIE_SECRET = 'secret';
var COOKIE_NAME = 'sid';

const socket = require('socket.io')
const express = require('express')
var session = require("express-session")
var sharedsession = require("express-socket.io-session")
var sessionStore = new session.MemoryStore()
const app = express()

var sessionMid = session({
    name: COOKIE_NAME,
    store: sessionStore,
    secret: COOKIE_SECRET,
    saveUninitialized: true,
    resave: true,
    cookie: {
        path: '/',
        httpOnly: true,
        secure: false,
        maxAge: null
    }
})

app.use(sessionMid)

var server = require('http').Server(app)
const io = require('socket.io')(server)
server.listen(3000)

io.use(sharedsession(sessionMid, {
  autoSave: true
}))

app.get('/' , function (req, res) {
  req.session.username = 'foo'
  res.sendFile(__dirname + '/index.html')
})

app.get('/1' , function (req, res) {
  res.send(req.session.username)
})

io.on('connection', function (socket) {
  socket.handshake.session.username = 'boom'
  console.log(socket.handshake.session.username)
});
```

## Html file

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title> </title>
</head>
<body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.7/socket.io.min.js"></script>  
  <script>
    var socket = io('http://localhost:3000')
  </script>
</body>
</html>
```

Also i wonder how you can manage to update session. Because `socket` does not have a response object and when trying to create session for first time , you will not be able to set cookie inside headers from `socket` method

**Comment by oskosk** [comment]
Hi @thetutlage . Let me check this code and get back to you in a while.

Aboout your question. when socket.io creates the first connection **on a browser**, the XHR call **does send** cookies that were set first on HTML loading by `express-session`. 

On the server side, every socket has a `.request` property representing the request used to create the connection. 

I'll check out your code, but I think I know what may be happening right now. And I may need to update the package.

**Comment by thetutlage** [comment]
Any updates ?

**Comment by gaurav21r** [comment]
@oskosk Any updates? :+1:

**Comment by rascada** [comment]
For me dosn't work either.

**Comment by thetutlage** [comment]
@rascada Logically you cannot get sessions work with sockets, especially if you are saving session inside a cookie. Socket.io does give the access to the handshake `http` request, but you cannot modify that request. 

That's why i am kinda surprised, how this module is managing to update sessions and waiting to see if it works.

**Comment by rascada** [comment]
It work if is manually saved with  `socket.handshake.session.save` method

**Comment by oskosk** [comment]
Hi guys. I'm sorry for disattending this topic. It did work for me but I've been kinda busy and didn't update this module for months. 

But it may have happened that something changed on *socket.io* and I did not update the code, so when you `npm install` you get a `socket.io` version newer that the one that worked with this. I think `socket.handshake` is not the same now and that I should be using `socket.conn.request` for getting the initial request object from the `socket.io` client that starts the request via XHR.

**Comment by DakshMiglani** [comment]
still didn't fix it :v
