### ISSUE TITLE
Lost on refresh

### ISSUE THREAD

**Issue by tallesdantas** [oskosk/express-socket.io-session#16]
Hi guys , i'm having a problem here , i run a nodejs server as a single server w/o rendering any html file, i usr it just to handle the sockets connection, the problem the code is as follow here:

```

session = require("express-session")({
	secret: "My secret",
	resave: true,
	saveUninitialized: true,
	cookie: { secure: true }
});

sharedsession = require("express-socket.io-session");

app.use(session); 

io.use(sharedsession(session, {
    autoSave:true
})); 

io.on('connection', function(socket){
  
  if(typeof socket.handshake.session.userdata != undefined)
  {
  	io.emit('Ulogedin',socket.handshake.session.userdata);

  }
   
 socket.on('login',function(msg){
          socket.handshake.session.userdata = 'New User o/ ';
});

}
...
```

the problem is that when i reload the page it generates a new socket connection and all the session is lost , how can i avoid the session lost after a page refresh?, can i destroy the session after 30 seconds user disconnected ?

**Comment by dodekeract** [comment]
Probably related to #6.

**Comment by tallesdantas** [comment]
nothing relates , different issue, it doesnt hold my session on page refresh

**Comment by dodekeract** [comment]
Did't you say, that you didn't deliver any HTML? The bug I reported was that socket sessions are only kept when HTML using shared-session was delivered. In case you don't deliver HTML, this bug is the same. In my tests you would always get a new session ID when reconnecting the socket **except** if you already got an HTML session.

**Comment by tallesdantas** [comment]
i dont deliver any html i want my socket to be a part of the html part
the front-end is cliend-side only

**Comment by dodekeract** [comment]
Then I don't get why you think the issue isn't the same.
