### ISSUE TITLE
nsp check

### ISSUE THREAD

**Issue by intralizee** [oskosk/express-socket.io-session#20]
nsp check finds 1 vulnerabilities found.
Regular Expression Denial of Service for ms@0.7.0 from dependency debug@2.1.3 in express-socket.io-session@1.3.1

Update module debug whenever you get the chance to not have nsp check show it in the log when ran.

**Comment by hulmgulm** [comment]
I've created a pull request which fixes this error.

**Comment by oskosk** [comment]
Thank you @hulmgulm

**Comment by oskosk** [comment]
Fixed by #23
