### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Gacnt** [oskosk/express-socket.io-session#22]
Hi just wondering if this project is still maintained, still seems to work perfectly but the last commit was 11 months ago, I know it doesn't need to be updated if it's working fine, but maybe just a readme bump or something would be great.

Nothing worse than finding something great that is no longer maintained and eventually falls off the planet. Thanks for the great plugin!

**Comment by oskosk** [comment]
Hi, yes. I'm willing to keep it up to date, but this year has been messy for my brain. 

Unfortunately, this project has received some feedback through issues. Mostly stuff I couldn't reproduce right away. But none, as a PR. 

If eventually, any PR comes up, I'll totally take care of it. 

What has happened is that I have not implemented anything new. Thanks for you message, tho, it makes me be willing to keep this updated. Any suggestions on improvements?

**Comment by Gacnt** [comment]
No suggestions here! It seems fine just the way it is, just a little
daunting when I choose to use something that hasn't seen activity for a
year or so, but nice to hear you still support it. Thanks!
