### ISSUE TITLE
Using Session Variables.

### ISSUE THREAD

**Issue by CodeLuca** [oskosk/express-socket.io-session#3]
Hey!
Really love the idea of the package, but I am a little confused with some things. For instance could you display how to access a session variable with socket.io with your package and display that you can access it in express too (using sessions obviously).

**Comment by oskosk** [comment]
I'm truly sorry for the dealy in my answer. I will clarify this, with some examples in the README.

**Comment by oskosk** [comment]
I added [example](https://github.com/oskosk/express-socket.io-session/tree/master/example) directory and improved the  [example in README.md](https://github.com/oskosk/express-socket.io-session#example)
