### ISSUE TITLE
typescript support?

### ISSUE THREAD

**Issue by BorntraegerMarc** [oskosk/express-socket.io-session#37]
Are there already typings published somewhere?

**Comment by oskosk** [comment]
Nope :(

**Comment by AylaJK** [comment]
@BorntraegerMarc [@types/express-socket.io-session](https://www.npmjs.com/package/@types/express-socket.io-session)

**Comment by Zaniyar** [comment]
How did you make this work with typescript?

> Property 'session' does not exist on type 'Handshake'.ts(2339)


```
io.on("connection", (socket: Socket) => {
            socket.on("message",userdata=>{
                socket.handshake.session.userdata = userdata;
                socket.handshake.session.save();
            })
});
```

**Comment by Zaniyar** [comment]
thx @BorntraegerMarc for closing this.
