### ISSUE TITLE
doesn't save session in database

### ISSUE THREAD

**Issue by kselax** [oskosk/express-socket.io-session#39]
Doesn't work. when I refresh page session saves, when save in socket.io in database ttl "seesionname" show not updated counter.
package.json:

`{
  "name": "test-socket",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "connect-redis": "^3.3.3",
    "cookie-parser": "^1.4.3",
    "express": "^4.16.3",
    "express-session": "^1.15.6",
    "express-socket.io-session": "^1.3.3",
    "jquery": "^3.3.1",
    "json-stringify-safe": "^5.0.1",
    "socket.io": "^2.1.1"
  }
}`

index.js:
`const express = require('express');
var io = require('socket.io');
const http = require('http');
const path = require( 'path' );
var stringify = require('json-stringify-safe');
var redis = require("redis");
var session = require('express-session');
var RedisStore = require('connect-redis')(session); // needs for express redis session

var client = redis.createClient();
var sharedsession = require("express-socket.io-session"); // needs for share session with socket.io

// var cookieParser = require('cookie-parser');

var app = express();
var server = http.Server(app);
var io = io(server);
var run = 0;

server.listen(3000, function(){
  console.log('Listening port 3000...');
});

// app.use(cookieParser());

// express-session

var session = session({
    store: new RedisStore({client: client}),
    cookie: {maxAge: 360000,}, // one second has 1000 mseconds
    secret: 'keyboard cat',
    resave: false, // force resave session even if client nothing do
    saveUninitialized: false,
});
app.use(session);

app.use( express.static( path.join( __dirname + "/public" ) ) );
app.use('/scripts', express.static( path.join(__dirname + '/node_modules/jquery/dist/')));

// app.get('/', function(req, res){
//   if (typeof req.session.view !== 'undefined') {
//     req.session.view++;
//   } else {
//     req.session.view = 0;
//   }
//
//   console.log('views = ' + req.session.view, req.session.cookie.maxAge);
//   res.send('views = ' + req.session.view);
// });

app.get('/', function(req, res){
  if (typeof req.session.view !== 'undefined') {
    req.session.view++;
  } else {
    req.session.view = 0;
  }
  console.log('app.get = ' + req.session.view);
  res.sendFile(__dirname + '/public/1index.html');
});

io.use(function(socket, next){
  run++;
  next();
});
io.use(function(socket, next){
  run++;
  next();
});

io.use(sharedsession(session, {
    autoSave:true
}));

io.on('connection', function(socket){
  if(socket.handshake.session.view === undefined){
    console.log('start = ' + socket.handshake.session.view);
    socket.handshake.session.view=0;
    socket.handshake.session.save();
  }
  console.log('views = ' + socket.handshake.session.view);
  console.log('a user connected, run = ' + run);
  socket.emit('message', stringify(socket.handshake.session));

  socket.on('add_one', function(msg){
    socket.handshake.session.view++;
    socket.handshake.session.save();
    socket.handshake.session.reload(function(err) {
    // this will give you the update session info
});
    console.log(socket.handshake.session.view);
    socket.emit('message', socket.handshake.session.view);
  });

  socket.on('set_zero', function(msg){
    socket.handshake.session.view = 0;
    // socket.handshake.session.save();
    socket.emit('message', socket.handshake.session.view);
  });
});
`
/public/1index.html:
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

  <button id="add_one">add +1 to views</button>
  <button id="set_zero">set up to 0</button>

  <script src="/scripts/jquery.js" charset="utf-8"></script>
  <script src="/socket.io/socket.io.js" charset="utf-8"></script>
  <script type="text/javascript">
    var io = io();
    io.on('message', function(msg){
      console.log(msg);
    });
    $('#add_one').click(function(event) {
      io.emit('add_one', '');
    });
    $('#set_zero').click(function(event) {
      io.emit('set_zero', '');
    });
  </script>
</body>
</html>
`
when I refresh I've got saved session view with counter +1 and refresh experation in redis, (ttl key new)
when I do the same using button over socket.io I got only counter +1 but expiration in redis left the same without refresh. (ttl key show the same timer)

**Comment by oskosk** [comment]
Should be fixed by #40
