### ISSUE TITLE
save session variables from socket.io

### ISSUE THREAD

**Issue by perrin4869** [oskosk/express-socket.io-session#4]
Hi, first of all, thanks for providing this elegant solution to sharing sessions!
I'm not sure if this is the expected behavior or not, since I couldn't find any examples for this, so I thought I'd ask - unlike with Express, where you can simply change the session data and it gets automatically saved, when using socket.handshake.session, you have to manually call save() on session in order to store the session, otherwise it gets lost. I'm using connect-mongo for the storage, with mongodb native driver, btw... Is this the expected behavior, or is there a problem in my setup?
Thanks!

**Comment by oskosk** [comment]
Thanks for the question. Let me clarifiy what's happening...

**express-session** when used as an express middleware, does this on the end of every request handling.

```
      if (shouldSave(req)) {
        req.session.save(function onsave(err) {
          if (err) {
            defer(next, err);
          }

          writeend();
        });
```

So the `shouldSave` method  checks the differences in the request session variables on _every request_ and if something changed it decides the session variables should be saved back to the session store.

In the case of using this module, **express-socket.io-session** which relies on the behaviour of **socket.io** middleware, this check is only done when **socket.io** client connects to the server. This is the only time **socket.io** middleware is executed, on the first HTTP request initiates the socket.io communication.

Thus, your code **inside a socket.io event handler** can access the session object, but does not run that piece of code that happens with every request in express. 

You have two options. 
* Always access variables with the asynchronous `session.get` inside a **socket.io** event handler. _And of course, use `session.save()` when altering values_.
* Help me figure out a change in the code of this module that makes things easier. :P I don't know if it's ok to make every event handler, reload/resave data from the mongodb (or redis, or whataver) automagically beacuse maybe it's only one of your event handlers among dozen others that needs this data updated. 

Given that, I'll will clarify this behavior in the README.

**Comment by oskosk** [comment]
I updated my previous reply, because I stated that `session.get()` was used to get current session values asyncrhonously... The function that you need to call when you are interested in getting updated values for session variables when you are inside socket.io event handler is `socket.handhsake.session.reload()`

**Comment by oskosk** [comment]
I added the explanation to the README.md under [Modifying session data inside socket.io event handlers](https://github.com/oskosk/express-socket.io-session#modifying-session-data-inside-socketio-event-handlers) and under [ More about updating and getting session data](https://github.com/oskosk/express-socket.io-session/blob/master/more-about-updating-and-getting-session-data)

**Comment by oskosk** [comment]
@perrin4869  Do you think I should monkeypatch the socket's ".on()" method for providing the same functionality that `express-session` provides? (I mean the autosave when all handlers are donde)

**Comment by perrin4869** [comment]
Well, it would be cool to give such option, as long as it's configurable - then why not!
Maybe provide an extra argument for the middleware constructor:

```
sharedsession(session, { autosave: true/false })
```
The question then would be, what should the default value be then? Maybe it'll be less confusing to make it the same behavior as with express.

**Comment by oskosk** [comment]
Sorry for the delay @perrin4869 . I don't know why I didn't get noticed about your last comment on May 10. I'll add this as a feature issue request.

**Comment by oskosk** [comment]
Implemented `autoSave:true` option. Please check it out and feel free to give me some feedback if it works as expected
