### ISSUE TITLE
Implement autoSave for session ala express-session wrapping a socket's on() method

### ISSUE THREAD

**Issue by oskosk** [oskosk/express-socket.io-session#7]
sharedsession(session, { autoSave: true/false })

Decide about the default

**Comment by MaxYari** [comment]
Hello oskosk! I think default is better to be false, as socket realtime app may be really intensive and make node run around on each request does not look like a good idea.
Btw in your codesnippet under Usage (on main package's github page) you passing `session` object twice - on require and on passing stuff to socket middleware, i suppose it's a typo?

**Comment by oskosk** [comment]
Damn. It's a typo and I think I introduced it on the last commit when trying to refactor that snippet in order for it to be simpler. But I messed it up.

Thanks!

Regarding the `autoSave` option I'll implement it as you recommend, defaulting  to `false`

**Comment by MaxYari** [comment]
No problem =)
 I had really annoying problems before trying to befriend passport writings to session with writings from sockets (session became unchangable after writing from sockets). Now implementing your module with hope that it finally going to work.
Thanks for making and maintaining it!

**Comment by oskosk** [comment]
I've updated the package to 1.3.0 . Implemented `autoSave`. Options. Let me know if it works as expected. Thanks @MaxYari !

**Comment by thebigredgeek** [comment]
This doesn't seem to be working...

**Comment by oskosk** [comment]
Hi Andrew. are you setting autoSave:true ?
