### ISSUE TITLE
express-session deprecated undefined

### ISSUE THREAD

**Issue by Dimatrii97** [oskosk/express-socket.io-session#73]
express-session deprecated undefined resave option; provide resave option node_modules\express-socket.io-session\index.js:79:4
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules\express-socket.io-session\index.js:79:4
express-session deprecated req.secret; provide secret option node_modules\express-socket.io-session\index.js:79:4
I'm not sure, but maybe I did something wrong?

**Comment by sanchezweezer** [comment]
Yes, you should set resave option (in express-session) to true or false (do not use default value)
https://www.npmjs.com/package/express-session#resave
